# Generated by Django 4.2 on 2024-04-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vehiculo_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chofer",
            name="vehiculo_id",
        ),
        migrations.RemoveField(
            model_name="registrocontabilidad",
            name="vehiculo_id",
        ),
        migrations.AddField(
            model_name="chofer",
            name="vehiculo",
            field=models.OneToOneField(
                default="autito",
                max_length=6,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehiculo_app.vehiculo",
            ),
        ),
        migrations.AddField(
            model_name="registrocontabilidad",
            name="vehiculo",
            field=models.OneToOneField(
                default="registro",
                max_length=6,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehiculo_app.vehiculo",
            ),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="patente",
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
