# Generated by Django 4.2 on 2024-04-30 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehiculo_app", "0002_remove_chofer_vehiculo_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chofer",
            old_name="vehiculo",
            new_name="vehiculo_id",
        ),
    ]
