# Generated by Django 4.2 on 2024-04-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehiculo_app", "0003_rename_vehiculo_chofer_vehiculo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="activo",
            field=models.BooleanField(default=False),
        ),
    ]
