# Generated by Django 4.2 on 2024-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehiculo_app", "0004_vehiculo_activo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chofer",
            name="creacion_reg",
            field=models.DateField(auto_now_add=True),
        ),
    ]
